apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: time
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: docker.io/veermuchandi/mytime:latest
    pushSecret:
      name: docker-registry
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: busybox
    git:
      uri: https://github.com/VeerMuchandi/time
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: busybox:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: FyRly4msApCtHMFNljb9
    type: GitHub
  - generic:
      secret: GCx5VujMy-QQ1yVS1TuK
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: busybox@sha256:fd4a8673d0344c3a7f427fe4440d4b8dfd4fa59cfabbd9098f9eb0cb4ba905d0
    type: ImageChange
status:
  lastVersion: 1
