apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: fun-jose-run1
spec:
  taskRef:
    name: s2i-php
  params:
    - name: TLSVERIFY
      value: 'false'
    - name: PATH_CONTEXT
      value: ./
  resources:
    inputs:
      - name: source
        resourceRef:
          name: patientui-git
    outputs:
      - name: image
        resourceRef:
          name: adminui-image
  serviceAccountName: pipeline