#https://github.com/tektoncd/pipeline/blob/master/docs/auth.md
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/git-0: https://github.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: opentlc-mgr
  password: 36Upn-3e1D8btUm0sRtlWeh9Z9qiTxjBfQqkFji2KV8
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder
secrets:
  - name: basic-user-pass